version: "3.3"
services:
  mongodb:
    image: mongo:latest # no mongo shell
    #image: mongo:5.0
    container_name: mongo_binance_historical
    volumes:
      - ./data:/data/db
      #- ./data2:/data/db2
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=userAdmin
      - MONGO_INITDB_ROOT_PASSWORD=userPassword

  postgres:
    image: postgres:14.2-alpine
    container_name: postgres_binance_stream
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=useradmin
      - POSTGRES_PASSWORD=userpassword
